![baby_names](baby_names.jpg)

How have American baby name tastes changed since 1920? Which names have remained popular for over 100 years, and how do those names compare to more recent top baby names? These are considerations for many new parents, but the skills you'll practice while answering these queries are broadly applicable. After all, understanding trends and popularity is important for many businesses, too!

You'll be working with data provided by the United States Social Security Administration, which lists first names along with the number and sex of babies they were given to in each year. For processing speed purposes, the dataset is limited to first names which were given to over 5,000 American babies in a given year. The data spans 101 years, from 1920 through 2020.

## The Data

### `baby_names`

| column         | type    | description                                                                  |
| -------------- | ------- | ------------------------------------------------------------------------ |
| `year`         | int     | year                                                                     |
| `first_name`   | varchar | first name                                                               |
| `sex`          | varchar | `sex` of babies given `first_name`                                       |
| `num`          | int     | number of babies of `sex` given `first_name` in that `year`              |

In [33]:
-- Run this code to view the data in baby_names
SELECT *
FROM baby_names
LIMIT 5;

   year first_name sex    num
0  1920       Mary   F  70982
1  1920    Dorothy   F  36643
2  1920      Helen   F  35097
3  1920   Margaret   F  27994
4  1920       Ruth   F  26101

In [34]:
-- Use this table for the answer to question 1:
-- List the overall top five names in alphabetical order and find out if each name is "Classic" or "Trendy."
SELECT first_name,
    SUM(num),
    CASE WHEN COUNT(DISTINCT year)>=50 THEN 'Classic'
         ELSE 'Trendy' END AS popularity_type
FROM baby_names
GROUP BY first_name
ORDER By first_name
LIMIT 5;

  first_name     sum popularity_type
0    Aaliyah   15870          Trendy
1      Aaron  530592         Classic
2    Abigail  338485          Trendy
3       Adam  497293          Trendy
4    Addison  107433          Trendy

In [35]:
-- Use this table for the answer to question 2:
-- What were the top 20 male names overall, and how did the name Paul rank?
SELECT RANK() OVER(ORDER BY num DESC) AS name_rank,
    first_name,
    SUM(num)
FROM baby_names
WHERE sex='M'
GROUP BY first_name,num
ORDER BY num DESC
LIMIT 20;

    name_rank first_name    sum
0           1      James  94764
1           2    Michael  92718
2           3     Robert  91647
3           4    Michael  90665
4           5    Michael  90564
5           6      James  88589
6           7    Michael  88576
7           8    Michael  88372
8           9       John  88319
9          10      James  87439
10         11      James  87261
11         12      James  87063
12         13    Michael  86917
13         14      James  86865
14         15     Robert  86597
15         16     Robert  86352
16         17     Robert  86341
17         18      David  86323
18         19      James  86319
19         20     Robert  86247

In [36]:
-- Use this table for the answer to question 3:
-- Which female names appeared in both 1920 and 2020?
SELECT first_name,
    SUM(num) AS total_occurrences
FROM baby_names
WHERE sex='F' AND year IN(1920,2020)
GROUP BY first_name
HAVING COUNT(DISTINCT year)=2;

  first_name  total_occurrences
0    Eleanor              14832
1  Elizabeth              23125
2       Emma              20818
3     Evelyn              23283
4      Grace              12741
5      Hazel              12765